all:
	javac Example.java 
	java Example 
	javac Example2.java
	java Example2
	javac ProducerConsumer.java
	java ProducerConsumer
	javac BalkingBoundedBuffer.java
	java BalkingBoundedBuffer
clean:
	rm -rf *.class
	clear
