'use strict';
function showform(){
	var forma=[
	'<div class ="container">',
	'	<section>',
	
	'	<form onsubmit="return registerData()" method = "post"',
	'		<div id = "content">',
	'		<input id = "username" type="text" placeholder="Username"  onChange = "photo_button()" pattern="[A-Za-z]{8,}" title="The username must be at least 8 characters long"required>',
	'		<div id = "picbox">',
	'			<input type="radio" name="pic"  id = "radiopic" value="takepic" onClick = "radio_button()"  />',
	'			<label for="takepic">Take my photo.</label>',
				
		'	</div>',
		'	<div id = "picbutton_box">',
	
		'	  <video id="video" width="640" height="480" autoplay></video>',
		'		  <input type="button"class = "locations"  id="snap" value ="Take Photo" onClick = "map_generator()">',
		'		  <input type="button" class = "locations"  id="upload" value ="Upload Image">',
		'		  <canvas id="canvas" width="640" height="480"></canvas>',
		'		  <script>',
		'			faceRec.init();',
		'		  </script>',
		'	</div>',
		'	<input id = "email" type="email" placeholder="E-mail"  pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" required> ',
		'	<div class = "boxtext">',
		'		<input id = "password" type="password" placeholder="Password" name="pw"  title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 to 10 characters" required>',
		'		<span  id = "psw_msg" class = "message"> </span>',
		'	</div>',
		'	<input id = "password2" type="password" placeholder="Confirm password" required >',
		
		'	<input id = "fname" type="text" placeholder="FirstName"  pattern="{3,15}" title="Must be between 3 and 15 characters "required>',
		'	<input id = "lname" type="text" placeholder="LastName" pattern="{3,15}" title="Must be between 3 and 15 characters "required>',
			
		'	<div id = "radiobox" >',
		'	<input type="radio" name="gender" value="male"  required checked/>',
		'	<label for="Male">Male</label>',
		'	<input type="radio" name="gender" value="female" required />',
		'	<label for="Female">Female</label>',
		'	<input type="radio" name="gender" value="other" required />',
		'	<label for="Other">Other</label> ',
		
		'	</div>',
		'	<div class = "boxtext">',
		'	<input type="date" id="bday" min="1930-01-01" max="2020-01-01" required>',
		'	</div>',
		'	<select  id = "countries" class="form-control" name="countries" required >',
			
		'		<option value="AF">Afghanistan</option>',
		'		<option value="AX">Åland Islands</option>',
		'		<option value="AL">Albania</option>',
		'		<option value="DZ">Algeria</option>',
		'		<option value="AS">American Samoa</option>',
		'		<option value="AD">Andorra</option>',
		'		<option value="AO">Angola</option>',
		'		<option value="AI">Anguilla</option>',
		'		<option value="AQ">Antarctica</option>',
		'		<option value="AG">Antigua and Barbuda</option>',
		'		<option value="AR">Argentina</option>',
		'		<option value="AM">Armenia</option>',
		'		<option value="AW">Aruba</option>',
		'		<option value="AU">Australia</option>',
		'		<option value="AT">Austria</option>',
		'		<option value="AZ">Azerbaijan</option>',
		'		<option value="BS">Bahamas</option>',
		'		<option value="BH">Bahrain</option>',
		'		<option value="BD">Bangladesh</option>',
		'		<option value="BB">Barbados</option>',
		'		<option value="BY">Belarus</option>',
		'		<option value="BE">Belgium</option>',
		'		<option value="BZ">Belize</option>',
		'		<option value="BJ">Benin</option>',
		'		<option value="BM">Bermuda</option>',
		'		<option value="BT">Bhutan</option>',
		'		<option value="BO">Bolivia, Plurinational State of</option>',
		'		<option value="BQ">Bonaire, Sint Eustatius and Saba</option>',
		'		<option value="BA">Bosnia and Herzegovina</option>',
		'		<option value="BW">Botswana</option>',
		'		<option value="BV">Bouvet Island</option>',
		'		<option value="BR">Brazil</option>',
		'		<option value="IO">British Indian Ocean Territory</option>',
		'		<option value="BN">Brunei Darussalam</option>',
		'		<option value="BG">Bulgaria</option>',
		'		<option value="BF">Burkina Faso</option>',
		'	<option value="BI">Burundi</option>',
		'		<option value="KH">Cambodia</option>',
		'		<option value="CM">Cameroon</option>',
		'		<option value="CA">Canada</option>',
		'		<option value="CV">Cape Verde</option>',
		'		<option value="KY">Cayman Islands</option>',
		'		<option value="CF">Central African Republic</option>',
		'		<option value="TD">Chad</option>',
		'		<option value="CL">Chile</option>',
		'		<option value="CN">China</option>',
		'		<option value="CX">Christmas Island</option>',
		'		<option value="CC">Cocos (Keeling) Islands</option>',
		'		<option value="CO">Colombia</option>',
		'		<option value="KM">Comoros</option>',
		'		<option value="CG">Congo</option>',
		'		<option value="CD">Congo, the Democratic Republic of the</option>',
		'		<option value="CK">Cook Islands</option>',
		'		<option value="CR">Costa Rica</option>',
		'		<option value="CI">Côte dIvoire</option>',
		'		<option value="HR">Croatia</option>',
		'		<option value="CU">Cuba</option>',
		'		<option value="CW">Curaçao</option>',
		'		<option value="CY">Cyprus</option>',
		'		<option value="CZ">Czech Republic</option>',
		'		<option value="DK">Denmark</option>',
		'		<option value="DJ">Djibouti</option>',
		'		<option value="DM">Dominica</option>',
		'		<option value="DO">Dominican Republic</option>',
		'		<option value="EC">Ecuador</option>',
		'		<option value="EG">Egypt</option>',
		'		<option value="SV">El Salvador</option>',
		'		<option value="GQ">Equatorial Guinea</option>',
		'		<option value="ER">Eritrea</option>',
		'		<option value="EE">Estonia</option>',
		'		<option value="ET">Ethiopia</option>',
		'		<option value="FK">Falkland Islands (Malvinas)</option>',
		'		<option value="FO">Faroe Islands</option>',
		'		<option value="FJ">Fiji</option>',
		'		<option value="FI">Finland</option>',
		'		<option value="FR">France</option>',
		'		<option value="GF">French Guiana</option>',
		'		<option value="PF">French Polynesia</option>',
		'		<option value="TF">French Southern Territories</option>',
		'		<option value="GA">Gabon</option>',
		'		<option value="GM">Gambia</option>',
		'		<option value="GE">Georgia</option>',
		'		<option value="DE">Germany</option>',
		'		<option value="GH">Ghana</option>',
		'		<option value="GI">Gibraltar</option>',
		'		<option selected value="GR">Greece</option>',
		'		<option value="GL">Greenland</option>',
		'		<option value="GD">Grenada</option>',
		'		<option value="GP">Guadeloupe</option>',
		'		<option value="GU">Guam</option>',
		'		<option value="GT">Guatemala</option>',
		'		<option value="GG">Guernsey</option>',
		'		<option value="GN">Guinea</option>',
		'		<option value="GW">Guinea-Bissau</option>',
		'		<option value="GY">Guyana</option>',
		'		<option value="HT">Haiti</option>',
		'		<option value="HM">Heard Island and McDonald Islands</option>',
		'		<option value="VA">Holy See (Vatican City State)</option>',
		'		<option value="HN">Honduras</option>',
		'		<option value="HK">Hong Kong</option>',
		'		<option value="HU">Hungary</option>',
		'		<option value="IS">Iceland</option>',
		'		<option value="IN">India</option>',
		'		<option value="ID">Indonesia</option>',
		'		<option value="IR">Iran, Islamic Republic of</option>',
		'		<option value="IQ">Iraq</option>',
		'		<option value="IE">Ireland</option>',
		'		<option value="IM">Isle of Man</option>',
		'		<option value="IL">Israel</option>',
		'		<option value="IT">Italy</option>',
		'		<option value="JM">Jamaica</option>',
		'		<option value="JP">Japan</option>',
		'		<option value="JE">Jersey</option>',
		'		<option value="JO">Jordan</option>',
		'		<option value="KZ">Kazakhstan</option>',
		'		<option value="KE">Kenya</option>',
		'		<option value="KI">Kiribati</option>',
		'		<option value="KP">Korea, Democratic People s Republic of</option>',
		'		<option value="KR">Korea, Republic of</option>',
		'		<option value="KW">Kuwait</option>',
		'		<option value="KG">Kyrgyzstan</option>',
		'		<option value="LA">Lao Peoples Democratic Republic</option>',
		'		<option value="LV">Latvia</option>',
		'		<option value="LB">Lebanon</option>',
		'		<option value="LS">Lesotho</option>',
		'		<option value="LR">Liberia</option>',
		'		<option value="LY">Libya</option>',
		'		<option value="LI">Liechtenstein</option>',
		'		<option value="LT">Lithuania</option>',
		'		<option value="LU">Luxembourg</option>',
		'		<option value="MO">Macao</option>',
		'		<option value="MK">Macedonia, the former Yugoslav Republic of</option>',
		'		<option value="MG">Madagascar</option>',
		'		<option value="MW">Malawi</option>',
		'		<option value="MY">Malaysia</option>',
		'		<option value="MV">Maldives</option>',
		'		<option value="ML">Mali</option>',
		'		<option value="MT">Malta</option>',
		'		<option value="MH">Marshall Islands</option>',
		'		<option value="MQ">Martinique</option>',
		'		<option value="MR">Mauritania</option>',
		'		<option value="MU">Mauritius</option>',
		'		<option value="YT">Mayotte</option>',
		'		<option value="MX">Mexico</option>',
		'		<option value="FM">Micronesia, Federated States of</option>',
		'		<option value="MD">Moldova, Republic of</option>',
		'		<option value="MC">Monaco</option>',
		'		<option value="MN">Mongolia</option>',
		'		<option value="ME">Montenegro</option>',
		'		<option value="MS">Montserrat</option>',
		'		<option value="MA">Morocco</option>',
		'		<option value="MZ">Mozambique</option>',
		'		<option value="MM">Myanmar</option>',
		'		<option value="NA">Namibia</option>',
		'		<option value="NR">Nauru</option>',
		'		<option value="NP">Nepal</option>',
		'		<option value="NL">Netherlands</option>',
		'		<option value="NC">New Caledonia</option>',
		'		<option value="NZ">New Zealand</option>',
		'		<option value="NI">Nicaragua</option>',
		'		<option value="NE">Niger</option>',
		'		<option value="NG">Nigeria</option>',
		'		<option value="NU">Niue</option>',
		'		<option value="NF">Norfolk Island</option>',
		'		<option value="MP">Northern Mariana Islands</option>',
		'		<option value="NO">Norway</option>',
		'		<option value="OM">Oman</option>',
		'		<option value="PK">Pakistan</option>',
		'		<option value="PW">Palau</option>',
		'		<option value="PS">Palestinian Territory, Occupied</option>',
		'		<option value="PA">Panama</option>',
		'		<option value="PG">Papua New Guinea</option>',
		'		<option value="PY">Paraguay</option>',
		'		<option value="PE">Peru</option>',
		'		<option value="PH">Philippines</option>',
		'		<option value="PN">Pitcairn</option>',
		'		<option value="PL">Poland</option>',
		'		<option value="PT">Portugal</option>',
		'		<option value="PR">Puerto Rico</option>',
		'		<option value="QA">Qatar</option>',
		'		<option value="RE">Réunion</option>',
		'		<option value="RO">Romania</option>',
		'		<option value="RU">Russian Federation</option>',
		'		<option value="RW">Rwanda</option>',
		'		<option value="BL">Saint Barthélemy</option>',
		'		<option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>',
		'		<option value="KN">Saint Kitts and Nevis</option>',
		'		<option value="LC">Saint Lucia</option>',
		'		<option value="MF">Saint Martin (French part)</option>',
		'		<option value="PM">Saint Pierre and Miquelon</option>',
		'		<option value="VC">Saint Vincent and the Grenadines</option>',
		'		<option value="WS">Samoa</option>',
		'		<option value="SM">San Marino</option>',
		'		<option value="ST">Sao Tome and Principe</option>',
		'		<option value="SA">Saudi Arabia</option>',
		'		<option value="SN">Senegal</option>',
		'		<option value="RS">Serbia</option>',
		'		<option value="SC">Seychelles</option>',
		'		<option value="SL">Sierra Leone</option>',
		'		<option value="SG">Singapore</option>',
		'		<option value="SX">Sint Maarten (Dutch part)</option>',
	'			<option value="SK">Slovakia</option>',
	'			<option value="SI">Slovenia</option>',
		'		<option value="SB">Solomon Islands</option>',
		'		<option value="SO">Somalia</option>',
		'		<option value="ZA">South Africa</option>',
		'		<option value="GS">South Georgia and the South Sandwich Islands</option>',
		'		<option value="SS">South Sudan</option>',
		'		<option value="ES">Spain</option>',
		'		<option value="LK">Sri Lanka</option>',
		'		<option value="SD">Sudan</option>',
		'		<option value="SR">Suriname</option>',
		'		<option value="SJ">Svalbard and Jan Mayen</option>',
		'		<option value="SZ">Swaziland</option>',
		'		<option value="SE">Sweden</option>',
		'		<option value="CH">Switzerland</option>',
		'		<option value="SY">Syrian Arab Republic</option>',
		'		<option value="TW">Taiwan, Province of China</option>',
		'		<option value="TJ">Tajikistan</option>',
		'		<option value="TZ">Tanzania, United Republic of</option>',
		'		<option value="TH">Thailand</option>',
		'		<option value="TL">Timor-Leste</option>',
		'		<option value="TG">Togo</option>',
		'		<option value="TK">Tokelau</option>',
		'		<option value="TO">Tonga</option>',
		'		<option value="TT">Trinidad and Tobago</option>',
		'		<option value="TN">Tunisia</option>',
		'		<option value="TR">Turkey</option>',
		'		<option value="TM">Turkmenistan</option>',
		'		<option value="TC">Turks and Caicos Islands</option>',
		'		<option value="TV">Tuvalu</option>',
		'		<option value="UG">Uganda</option>',
		'		<option value="UA">Ukraine</option>',
		'		<option value="AE">United Arab Emirates</option>',
		'		<option value="GB">United Kingdom</option>',
		'		<option value="US">United States</option>',
		'		<option value="UM">United States Minor Outlying Islands</option>',
		'		<option value="UY">Uruguay</option>',
		'		<option value="UZ">Uzbekistan</option>',
		'		<option value="VU">Vanuatu</option>',
		'		<option value="VE">Venezuela, Bolivarian Republic of</option>',
		'		<option value="VN">Viet Nam</option>',
		'		<option value="VG">Virgin Islands, British</option>',
		'		<option value="VI">Virgin Islands, U.S.</option>',
		'		<option value="WF">Wallis and Futuna</option>',
		'		<option value="EH">Western Sahara</option>',
		'		<option value="YE">Yemen</option>',
		'		<option value="ZM">Zambia</option>',
		'		<option value="ZW">Zimbabwe</option>',
		'	</select>',
			
		'	<input id = "Address"type="text" placeholder="Address"  pattern="{2,40}">',
		'	<div class = "boxtext">',
			'	<input id = "City" type="text" placeholder="City"  onChange = "checkmap()"  pattern="{2,20}" title="Must be between 2 and 20 characters "required>',
			'	<span  id = "city_msg" class = "message"> </span>',
			'</div>',
			'<br/>',
	
			
			'<div id = "map_box">',
			'	<button id = "trackLoc" class = "locations" onClick = "map_generator()">Track existing location</button>',
			'	<button id = "trackMe" class = "locations" onClick = "track()">Track your location</button>',
			'</div>',
		
			'<div id = "work">',
			'	<input type="text" placeholder="Work" id="work" pattern="{3,15}" title="Must be between 3 and 15 characters "required>',
			'	<input type="text" placeholder="Interests" id="interest" pattern="{0,100}" title="Must be between 3 and 15 characters ">',
			'	<br/>',
			'</div>',
			'<br/>',
			'<input id = " but" class = "locations" type="submit" value="Register" onClick = "registerData()">',
			'</div>',

		'</form>',
		'</section>',
                '</div>'
	].join("\n");
	
	document.getElementById("content_index").innerHTML = forma;
}