all:
	gcc -o helloworld_openmp helloworld_openmp.c -fopenmp
	gcc -o ask1 ask1.c -fopenmp
	gcc -o fibonacci_openmp fibonacci_openmp.c -fopenmp
	gcc -o j_print j_print.c -fopenmp
clean:
	rm -rf helloworld_openmp
	rm -rf ask1
	rm -rf fibonacci_openmp
	rm -rf j_print
	clear
 
