all:
	gcc -o hello_from_threads hello_from_threads.c -pthread
	gcc -o parallelfor parallelfor.c -pthread
	gcc -o Levenshtein Levenshtein.c -pthread
	gcc -o mergesort mergesort.c -pthread
	gcc -o parallel_mergesort parallel_mergesort.c -pthread
	gcc -o parallel_Levenshtein parallel_Levenshtein.c -pthread
	gcc -o bugThema2020 bugThema2020.c -pthread
clean:
	rm -rf hello_from_threads
	rm -rf parallelfor
	rm -rf Levenshtein
	rm -rf mergesort
	rm -rf parallel_mergesort
	rm -rf parallel_Levenshtein
	rm -rf bugThema2020	
	clear
 
